#!/bin/sh
#------------------------------------------------------------
# Zabbix agent installation
# Created by Inga on 26/02/2021
#------------------------------------------------------------
# Input: machine hostname where zabbix installation need be done - only one machine
# Output: N/A
# Process:
#         1) Check the version of Oracle Linux and that getenforce is disable
#         2) Check that zabbix is not installed on this machine
#         3) Install zabbix agent
#         4) Save the original zabbix_agentd.conf as zabbix_agentd.conf.orig
#         5) Update zabbix_agentd.conf with 
#                    Zabbix Server IP = 172.20.7.235 (slwk) and
#                    Hostanme = HPC_zabbix
#         6) Start and enable zabbix-agent
#         7) Check if zabbix-agent is running:
#         7a) If yes: 
#                   7a.a) save machine IP & hostname inside /gpfs0/system/zabbix_storage/zabbix_IP_list.txt
#                   7a.b) save machine hostname /gpfs0/system/zabbix_storage/zabbix_hostname_list.txt
#         7b) If not:
#                   7b.a) print error for this machine
#
#         ***) Not in this script but need be done after completion of the script:
#                         update Zabbix frontend Name = HPC_zabbix  with the new IP (use machine_IP.txt file)
#                         http://132.72.137.175:8080/zabbix/hosts.php    
#-----------------------------------------------------------

#------------------------------------------------------------
# 1)  Check the version of Oracle Linux and that getenforce is disable
#------------------------------------------------------------
echo
echo ".................................................................."
echo -e "   \e[38;5;256mCheck if getenforce is disable \e[0m"
echo ".................................................................."

getenforce_check=$(getenforce)
if [ "$getenforce_check" == "Disabled" ]; then
       	echo -e "   \e[32mOK\e[0m: getenforce is disable"
else
	echo -e "   \e[35mWARNING!\e[0m Please disable getenforce"
	exit
fi

echo
echo ".................................................................."
echo -e "   \e[38;5;256mCheck the version of Oracle Linux  \e[0m"
echo ".................................................................."

OL_ver=$(cat /etc/oracle-release | awk '{print $5}'|cut -d. -f1)
if [ $OL_ver -lt 6 ]; then
	echo -e "   \e[35mWARNING!\e[0m Oracle Linux version below 6, please update Oracle linux"
	exit
else
	echo -e "   \e[32mOK\e[0m:"   $(cat /etc/oracle-release) 
fi

#------------------------------------------------------------
# 2) Check that zabbix is not installed on this machine
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mCheck if zabbix already exists  \e[0m"
echo ".................................................................."

zabbix_installed=$(ps -ef | grep zabbix | grep -v grep | grep -v zabbix_install)
if [ -z "$zabbix_installed" ]; then
	echo -e "   \e[32mOK\e[0m: Zabbix does not exist"
else
	echo -e "   \e[35mWARNING!\e[0m Zabbix already exists"
	exit
fi
echo

#------------------------------------------------------------
# 3) Install zabbix agent
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mrpm download  \e[0m"
echo ".................................................................."
#rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
echo -e "   \e[32mOK\e[0m: rpm successfully downloaded"
echo

echo ".................................................................."
echo -e "   \e[38;5;256mZabbix instalation  \e[0m"
echo ".................................................................."
#dnf install zabbix-agent -y
echo -e "   \e[32mOK\e[0m: Zabbix installed"
echo

#------------------------------------------------------------
# 4)Save the original zabbix_agentd.conf as zabbix_agentd.conf.orig 
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mSave the original zabbix_agentd.conf as zabbix_agentd.conf.orig  \e[0m"
echo ".................................................................."

cd /etc/zabbix/
cp -f zabbix_agentd.conf zabbix_agentd.conf.orig
echo

#------------------------------------------------------------
# 5) Update zabbix_agentd.conf with
#          Zabbix Server IP = 172.20.7.235 (slwk) and
#          Hostanme = HPC_zabbix
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mUpdate zabbix_agentd.conf file  \e[0m"
echo ".................................................................."

sge_ip=$(hostname -I | awk -F " " '{print $1}' )
zabbix_host_name=HPC_zabbix
sed -i "s/Server=127.0.0.1/Server=$sge_ip" zabbix_agentd.conf
sed -i "s/Hostname=Zabbix server/Hostname=$zabbix_host_name" zabbix_agentd.conf


echo

#------------------------------------------------------------
# 6) Start and enable zabbix-agent
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mStart and enable zabbix-agent  \e[0m"
echo ".................................................................."

# systemctl start zabbix-agent
# systemctl enable zabbix-agent

echo

#------------------------------------------------------------
# 7) Check if zabbix-agent is running
#         7a) If yes:
#                   7a.a) save machine IP & hostname inside /gpfs0/system/zabbix_storage/zabbix_IP_list.txt
#                   7a.b) save machine hostname /gpfs0/system/zabbix_storage/zabbix_hostname_list.txt
#         7b) If not:
#                   7b.a) print error for this machine
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256m Check if zabbix-agent is running  \e[0m"
echo ".................................................................."

GPFS=/gpfs0/system/zabbix_storage
if [ ! -f $GPFS/zabbix_IP_list.txt ]; then
	touch $GPFS/zabbix_IP_list.txt
fi
if [ ! -f $GPFS/zabbix_hostname_list.txt ]; then
	touch $GPFS/zabbix_hostname_list.txt
fi

#zabbix_installed=$(ps -ef | grep zabbix | grep -v grep | grep -v zabbix_install)
#if [ -z "$zabbix_installed" ]; then
#	echo -e "   \e[35mWARNING!\e[0m Zabbix is not running. Please T/S."
#	exit
#else
#	echo -e "   \e[32mOK\e[0m: Zabbix is running"
#	sge_ip=$(hostname -I | awk -F " " '{print $1}' )
#	sge_hostname=$(hostname)
#	echo $sge_ip >> $GPFS/zabbix_IP_list.txt
#	echo $sge_hostname >> $GPFS/zabbix_hostname_list#
#fi



echo
echo "END OF THE SCRIPT. By-by"
echo





