#!/bin/sh
#------------------------------------------------------------
# Zabbix agent installation on Centos8 VM: slc1, slc2, slwk (server), sldb
# Created by Inga on 26/02/2021
#------------------------------------------------------------
# Input: machine hostname where zabbix installation need be done - only one machine
# Output: N/A
# Process:
#         1) Check the version of Centos  and that getenforce is disable
#         2) Check that zabbix is not installed on this machine
#         3) Install zabbix agent
#         4) Save the original zabbix_agentd.conf as zabbix_agentd.conf.orig
#         5) Update zabbix_agentd.conf with 
#                    Zabbix Server IP = 172.20.7.235 (zabbix frontend => slwk) and
#                    Hostanme = HPC_OL8 (the name of group in the frontend web page)
#         6) Start and enable zabbix-agent
#         7) Check if zabbix-agent is running:
#         7a) If yes: 
#                   7a.a) save machine IP & hostname inside /gpfs0/system/zabbix_storage/zabbix_IP_list.txt
#                   7a.b) save machine hostname /gpfs0/system/zabbix_storage/zabbix_hostname_list.txt
#         7b) If not:
#                   7b.a) print error for this machine
#
#         ***) Not in this script but need be done after completion of the script:
#                         update Zabbix frontend Name = HPC_OL8  with the new IP (use machine_IP.txt file)
#                         zabbix web page => http://132.72.137.175:8080/zabbix/hosts.php    
#-----------------------------------------------------------

#------------------------------------------------------------
# Initializations
#------------------------------------------------------------

# For (2) where grep will remove matchin of the running of the current script
script_name=zabbix_agent_install

# For (5) zabbix_agentd.conf update
default_IP="Server=127.0.0.1" 
correct_IP="Server=172.20.7.235"

default_group_name="Hostname=Zabbix server"
correct_group_name="Hostname=VM"

default_active_IP="ServerActive=127.0.0.1"
correct_active_IP="#ServerActive=127.0.0.1"

# For (7) storage path where IP & hostnames of the machine 
# where zabbix agent was successfully installed will be saved
GPFS=/gpfs0/system/zabbix_storage

#------------------------------------------------------------
# 1)  Check the version of Oracle Linux and that getenforce is disable
#------------------------------------------------------------
echo
echo ".................................................................."
echo -e "   \e[38;5;256mCheck if getenforce is disable \e[0m"
echo ".................................................................."

getenforce_check=$(getenforce)
if [ "$getenforce_check" == "Disabled" ]; then
       	echo -e "   \e[32mOK\e[0m: getenforce is disable"
else
	echo -e "   \e[35mWARNING!\e[0m Please disable getenforce"
	exit
fi

echo
echo ".................................................................."
echo -e "   \e[38;5;256mCheck the version of Centos  \e[0m"
echo ".................................................................."

OL_ver=$(cat /etc/centos-release | awk '{print $5}'|cut -d. -f1)
if [ $OL_ver -lt 6 ]; then
	echo -e "   \e[35mWARNING!\e[0m Oracle Linux version below 6, please update Oracle linux"
	exit
else
	echo -e "   \e[32mOK\e[0m:"   $(cat /etc/oracle-release) 
fi

#------------------------------------------------------------
# 2) Check that zabbix is not installed on this machine
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mCheck if zabbix already exists  \e[0m"
echo ".................................................................."

zabbix_installed=$(ps -ef | grep zabbix | grep -v grep | grep -v $script_name)
if [ -z "$zabbix_installed" ]; then
	echo -e "   \e[32mOK\e[0m: Zabbix does not exist"
else
	echo -e "   \e[35mWARNING!\e[0m Zabbix already exists"
	exit
fi
echo

#------------------------------------------------------------
# 3) Install zabbix agent
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mrpm download  \e[0m"
echo ".................................................................."
rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
echo -e "   \e[32mOK\e[0m: rpm successfully downloaded"
echo

echo ".................................................................."
echo -e "   \e[38;5;256mZabbix instalation  \e[0m"
echo ".................................................................."
dnf install zabbix-agent -y
echo -e "   \e[32mOK\e[0m: Zabbix installed"
echo

#------------------------------------------------------------
# 4)Save the original zabbix_agentd.conf as zabbix_agentd.conf.orig 
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mSave the original zabbix_agentd.conf as zabbix_agentd.conf.orig  \e[0m"
echo ".................................................................."

cd /etc/zabbix/
cp -f zabbix_agentd.conf zabbix_agentd.conf.orig
echo

#------------------------------------------------------------
# 5) Update zabbix_agentd.conf with
#          Zabbix Server IP = 172.20.7.235 (slwk) and
#          Hostanme = HPC_zabbix
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mUpdate zabbix_agentd.conf file  \e[0m"
echo ".................................................................."

sed -i "s|$default_IP|$correct_IP|" zabbix_agentd.conf
sed -i "s|$default_group_name|$correct_group_name|" zabbix_agentd.conf
sed -i "s|$default_active_IP|$correct_active_IP|" zabbix_agentd.conf
echo

#------------------------------------------------------------
# 6) Start and enable zabbix-agent
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256mEnable zabbix-agent  \e[0m"
echo ".................................................................."
systemctl enable zabbix-agent
echo

echo ".................................................................."
echo -e "   \e[38;5;256mStart zabbix-agent  \e[0m"
echo ".................................................................."
systemctl start zabbix-agent
echo

echo ".................................................................."
ECHO -E "   \E[38;5;256MStatus of zabbix-agent  \e[0m"
echo ".................................................................."
systemctl status zabbix-agent
echo

#------------------------------------------------------------
# 7) Check if zabbix-agent is running
#         7a) If yes:
#                   7a.a) save machine IP & hostname inside /gpfs0/system/zabbix_storage/zabbix_IP_list.txt
#                   7a.b) save machine hostname /gpfs0/system/zabbix_storage/zabbix_hostname_list.txt
#         7b) If not:
#                   7b.a) print error for this machine
#------------------------------------------------------------
echo ".................................................................."
echo -e "   \e[38;5;256m Check if zabbix-agent is running  \e[0m"
echo ".................................................................."

if [ ! -f $GPFS/zabbix_IP_list.txt ]; then
	touch $GPFS/zabbix_IP_list.txt
fi
if [ ! -f $GPFS/zabbix_hostname_list.txt ]; then
	touch $GPFS/zabbix_hostname_list.txt
fi

zabbix_installed=$(ps -ef | grep zabbix | grep -v grep | grep -v zabbix_install)
if [ -z "$zabbix_installed" ]; then
	echo -e "   \e[35mWARNING!\e[0m Zabbix is not running. Please T/S."
	exit
else
	echo -e "   \e[32mOK\e[0m: Zabbix is running"
	sge_ip=$(hostname -I | awk -F " " '{print $1}' )
	sge_hostname=$(hostname)
	echo $sge_ip >> $GPFS/zabbix_IP_list.txt
	echo $sge_hostname >> $GPFS/zabbix_hostname_list.txt
fi



echo
echo "END OF THE SCRIPT. By-by"
echo





